// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package orm

import (
	"context"

	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
)

type DBTX interface {
	Query(context.Context, string, ...interface{}) (driver.Rows, error)
	QueryRow(context.Context, string, ...interface{}) driver.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}
