// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: hello.sql

package orm

import (
	"context"
)

const trade = `-- name: Trade :many
SELECT id, crypto_id, trade_volume, time_diff FROM trade_volume_1h
`

func (q *Queries) Trade(ctx context.Context) ([]TradeVolume1m, error) {
	rows, err := q.db.Query(ctx, trade)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TradeVolume1m{}
	for rows.Next() {
		var i TradeVolume1m
		if err := rows.Scan(
			&i.ID,
			&i.CryptoID,
			&i.TradeVolume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
