// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package orm

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Currency struct {
	ID          uuid.UUID `json:"id" ch:"id"`
	Name        string    `json:"name" ch:"name"`
	Code        string    `json:"code" ch:"code"`
	MaxSupply   int64     `json:"max_supply" ch:"max_supply"`
	Description string    `json:"description" ch:"description"`
}

type Index struct {
	ID          int64            `json:"id"`
	CryptoID    int64            `json:"crypto_id"`
	PriceIndex  int32            `json:"price_index"`
	VolumeIndex float64          `json:"volume_index"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Price struct {
	ID        int64            `json:"id"`
	CryptoID  int64            `json:"crypto_id"`
	Value     pgtype.Numeric   `json:"value"`
	MarketCap int32            `json:"market_cap"`
	TimeDiff  interface{}      `json:"time_diff"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Supply struct {
	ID          int64            `json:"id"`
	CryptoID    int64            `json:"crypto_id"`
	TotalSupply pgtype.Int8      `json:"total_supply"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type TradeVolume1h struct {
	ID          int64       `json:"id"`
	CryptoID    int64       `json:"crypto_id"`
	TradeVolume float64     `json:"trade_volume"`
	TimeDiff    interface{} `json:"time_diff"`
}

type TransactionPerDay struct {
	ID         int64            `json:"id"`
	CryptoID   int64            `json:"crypto_id"`
	TransValue int64            `json:"trans_value"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}
