// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package orm

import (
	"context"
)

type Querier interface {
	Trade(ctx context.Context) ([]TradeVolume1m, error)
}

var _ Querier = (*Queries)(nil)
