app:
  name: "crypto"
  env: "dev"
  version: "v1"

http:
  url: "https://crypto-scanner-vlad.com"
  port: 8005
  host: "localhost"
  read_timeout: "3s"
  write_timeout: "3s"

crypto:
  url: "https://min-api.cryptocompare.com/data"
  key: "1d83232e5c10b78e579ec38c6ebdab7fdaa0ea03ae2aa7289bac8efc2b065d64"

sql:
  host: "clickhouseDB"
  port: "9000"
  database: "cryptowallet"
  user: "default"
  password: ""
  read_timeout: "4s"
  write_timeout: "4s"
  timeout: "4s"


